name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest-ubuntu
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install && pnpm build
      - uses: ./
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
